Select *
from VEN.STOCKRECOMMENDATIONTABLE;

Create View Ven.WhatToBuyView as
Select STOCKSYMBOL, COUNT(STOCKSYMBOL) as count
from VEN.STOCKRECOMMENDATIONTABLE
group by STOCKSYMBOL
order by count desc;

Create View Ven.PNLTotal as
(Select SUM(PNL) as PNLTotal from Ven.PnLStockOnlyView) ;

select * from Ven.POSITIONTABLE where AssetType = 'Equity' and SYMBOL not in
                                      (Select STOCKSYMBOL from Ven.STOCKRECOMMENDATIONTABLE)

Select distinct (STOCKSYMBOL) from STOCKRECOMMENDATIONTABLE ;

-- auto-generated definition
-- auto-generated definition

drop table Ven.POSITIONTABLE;

create table Ven.POSITIONTABLE
(
    "SYMBOL"       VARCHAR(100) not null,
    "QUANTITY"     DECIMAL (8,2) not null,
    "COSTPERSHARE" DECIMAL(8,2)  not null,
    "ASSETTYPE"    VARCHAR(100) not null
);

create index POSITIONTABLE_SYMBOL_INDEX
    on Ven.POSITIONTABLE (SYMBOL);

Create VIEW Ven.WhatToBuyNowView as
(Select *
from Ven.STOCKRECOMMENDATIONTABLE
where Ven.STOCKRECOMMENDATIONTABLE.RECOMMENDEDBY not like '%SELL%'
  and Ven.STOCKRECOMMENDATIONTABLE.RECOMMENDEDBY not like '%HOLD%'
  and Ven.STOCKRECOMMENDATIONTABLE.STOCKSYMBOL not in
      (Select SYMBOL  from Ven.POSITIONTABLE  ) );

Create VIEW Ven.OptionsOnlyView as
(Select *
from Ven.POSITIONTABLE
where Ven.POSITIONTABLE.ASSETTYPE = 'Option');


Create VIEW Ven.StockOnlyView as
(Select *
from Ven.POSITIONTABLE
where Ven.POSITIONTABLE.ASSETTYPE = 'Equity');

Create VIEW Ven.PnLStockOnlyView as
Select Ven.MARKETPRICE.SYMBOL as Symbol,
       Ven.MARKETPRICE.PRICE*Ven.POSITIONTABLE.QUANTITY as "CURRENT",
       Ven.POSITIONTABLE.COSTPERSHARE*Ven.POSITIONTABLE.QUANTITY as COSTBASIS,
      Ven.MARKETPRICE.PRICE*Ven.POSITIONTABLE.QUANTITY -
       Ven.POSITIONTABLE.COSTPERSHARE*Ven.POSITIONTABLE.QUANTITY as PNL
from Ven.MARKETPRICE , Ven.POSITIONTABLE
where Ven.MARKETPRICE.SYMBOL = Ven.POSITIONTABLE.SYMBOL and
      Ven.POSITIONTABLE.ASSETTYPE='Equity';



drop view Ven.HowMuchToBuyOfWhat;

Create View Ven.HowMuchToBuyOfWhat as
(Select STOCKSYMBOL, PRICE , CAST( (1000/PRICE)+1 as INT) as HowMuch
from Ven.WhatToBuyNowView, Ven.MARKETPRICE where STOCKSYMBOL=SYMBOL);

Select * from ven.SYMBOLSTABLE where SYMBOL not in (Select SYMBOL from Ven.MARKETPRICE)


insert into Ven.MARKETPRICE
    (select STOCKSYMBOL, 0,0 from Ven.WhatToBuyNowView where Ven.WhatToBuyNowView.STOCKSYMBOL not in (Select SYMBOL from MARKETPRICE))

-- Process to update positions
-- TD Ameritrade , Get Positions Simple view, Format columns as numbers
-- Delete All Rows, Paste All rows..

--

select distinct (STOCKSYMBOL) from Ven.WhatToBuyNowView;
Select * from Ven.STOCKRECOMMENDATIONTABLE
where STOCKSYMBOL in
(Select HOWMUCHTOBUYOFWHAT.STOCKSYMBOL from Ven.HowMuchToBuyOfWhat);

Select * from Ven.HOWMUCHTOBUYOFWHAT, Ven.STOCKRECOMMENDATIONTABLE
where Ven.HOWMUCHTOBUYOFWHAT.STOCKSYMBOL = Ven.STOCKRECOMMENDATIONTABLE.STOCKSYMBOL;



---

Select Sum(Price*HowMuch) from Ven.HowMuchToBuyOfWhat;

---
Select STOCKSYMBOL, Price, HowMuch, (Price*HowMuch) as Cost from Ven.HowMuchToBuyOfWhat;

--
Create View Ven.CostView as
Select a.SYMBOL, a.COSTPERSHARE, a.QUANTITY, (a.COSTPERSHARE*a.QUANTITY) as Cost
from
     Ven.POSITIONTABLE a
where a.SYMBOL in (Select distinct(STOCKSYMBOL) from Ven.STOCKRECOMMENDATIONTABLE);

--
--

drop view Ven.PNLVIEW;

Create View Ven.PNLView as
Select a.SYMBOL, a.COSTPERSHARE, a.QUANTITY, (a.COSTPERSHARE*a.QUANTITY) as Cost,
       (p.PRICE*a.QUANTITY) as CurrentValue,  (p.PRICE*a.QUANTITY) - (a.COSTPERSHARE*a.QUANTITY) as PnL
from
     Ven.POSITIONTABLE a, Ven.MARKETPRICE p
where a.SYMBOL = p.SYMBOL and
 a.SYMBOL in (Select distinct(STOCKSYMBOL) from Ven.STOCKRECOMMENDATIONTABLE);


Create View Ven.TotalPNL as
Select Sum( (p.PRICE*a.QUANTITY) - (a.COSTPERSHARE*a.QUANTITY) ) as TotalPnL
from
     Ven.POSITIONTABLE a, Ven.MARKETPRICE p
where a.SYMBOL = p.SYMBOL and
 a.SYMBOL in (Select distinct(STOCKSYMBOL) from Ven.STOCKRECOMMENDATIONTABLE);

--
Select a.SYMBOL, a.QUANTITY, a.COSTPERSHARE,  a.QUANTITY*a.COSTPERSHARE , b.RECOMMENDEDBY from Ven.POSITIONTABLE a, Ven.STOCKRECOMMENDATIONTABLE b
where a.SYMBOL = b.STOCKSYMBOL and ((a.COSTPERSHARE*a.QUANTITY) <800)
--
Select  a.SYMBOL, b.COSTPERSHARE, b.QUANTITY, (b.QUANTITY*b.COSTPERSHARE) as Cost , c.RECOMMENDEDBY, d.PRICE as MktPrice,
       (d.PRICE-b.COSTPERSHARE)*100/b.COSTPERSHARE as  "Percent"
from Ven.WHATTOGETNOWUNDRBOUGHT a, Ven.POSITIONTABLE b,
   Ven.STOCKRECOMMENDATIONTABLE c, Ven.MARKETPRICE d, Ven.WhatToGetNowUndrbought800 e
where a.SYMBOL=b.SYMBOL and  c.STOCKSYMBOL=b.SYMBOL and c.STOCKSYMBOL=d.SYMBOL and c.STOCKSYMBOL=e.SYMBOL and
      b.QUANTITY*b.COSTPERSHARE < 800 and e.COUNT = 2;
--

Select  b.SYMBOL, d.price, b.COSTPERSHARE, b.QUANTITY, (b.QUANTITY*b.COSTPERSHARE) as Cost , d.PRICE as MktPrice, (b.QUANTITY*d.PRICE) as Value,
       (d.PRICE-b.COSTPERSHARE)*100/b.COSTPERSHARE as  "Percent"
from Ven.POSITIONTABLE b,
    Ven.MARKETPRICE d
where  b.SYMBOL=d.SYMBOL order by b.SYMBOL;
---
Select Sum (a.COSTPERSHARE*a.QUANTITY)   from Ven.POSITIONTABLE a where a.ASSETTYPE='Option' ;

Select Sum (a.COSTPERSHARE*a.QUANTITY) , Sum(a.QUANTITY*b.PRICE)  from Ven.POSITIONTABLE a, Ven.MARKETPRICE b where a.ASSETTYPE='Equity' and a.SYMBOL=b.SYMBOL;

Select a.SYMBOL, (a.COSTPERSHARE*a.QUANTITY) , a.QUANTITY*b.PRICE  from Ven.POSITIONTABLE a, Ven.MARKETPRICE b where a.SYMBOL=b.SYMBOL;
--
Create view Ven.WhatToGetNowUndrbought800 as
(Select a.STOCKSYMBOL as SYMBOL,  count(a.STOCKSYMBOL) as COUNT from Ven.STOCKRECOMMENDATIONTABLE a
where a.STOCKSYMBOL in (Select a.SYMBOL from Ven.POSITIONTABLE a, Ven.STOCKRECOMMENDATIONTABLE b
where a.SYMBOL = b.STOCKSYMBOL and a.COSTPERSHARE*a.QUANTITY <800)
group by STOCKSYMBOL);

Select a.SYMBOL from Ven.POSITIONTABLE a, Ven.STOCKRECOMMENDATIONTABLE b
where a.SYMBOL = b.STOCKSYMBOL and (a.COSTPERSHARE*a.QUANTITY) <800

-----
Select Sum(Price) from Ven.HOWMUCHTOBUYOFWHAT;
---

-- Find Symbols that have positions but are not being tarcked.
Select a.SYMBOL from ven.POSITIONTABLE a where a.ASSETTYPE = 'Equity'
                                           and  a.SYMBOL not in (Select SYMBOL from Ven.SYMBOLSTABLE)
--REMOVE DUPS FROM STOCK SYMBOLS
Select a.SYMBOL from ven.POSITIONTABLE a where a.ASSETTYPE = 'Equity'
                                           and  a.SYMBOL not in (Select SYMBOL from Ven.MARKETPRICE)


--


Select SUM(PRICE*HOWMUCH) from Ven.HowMuchToBuyOfWhat;

drop table TempX;
create table  TempX (SYMBOL) AS
    Select * from Ven.SYMBOLSTABLE WITH NO DATA;

insert into TempX  (Select distinct(SYMBOL) from Ven.SYMBOLSTABLE);

truncate table Ven.SYMBOLSTABLE;

insert into Ven.SYMBOLSTABLE  (Select distinct(SYMBOL) from TempX);

--------------------------


INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('AXON', 'RULEBREAKER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('Z', 'RULEBREAKER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MRNA', 'RULEBREAKER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'RULEBREAKER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NEE', 'RULEBREAKER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRM', 'RULEBREAKER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LMND', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PINS', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('RDFN', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRWD', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ESTC', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FLGT', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FVRR', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OPEN', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('KNSL', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NVTA', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PAYC', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SHOP', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TSLA', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TTD', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIX', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'BMGOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DDOG', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ETSY', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FSLY', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('GLOB', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HUBS', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LOB', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDB', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MGNI', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NOW', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OKTA', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPCE', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VCYT', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WD', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZS', 'BMSILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BOMN', 'BMBRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HCAT', 'BMBRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CLOV', 'BMBRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PTON', 'BMBRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ROKU', 'BMBRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TDOC', 'BMBRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TWLO', 'BMBRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WORK', 'BMBRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('COUP', 'BMSELL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SHOP', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TSLA', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FB', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MA', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ANET', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PAYC', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TTD', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CMG', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SIVB', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZS', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PRLB', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WD', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OKTA', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('Z', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('KNSL', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SBUX', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIX', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SQ', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TWLO', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ALGN', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MKL', 'EVERLASTINGPORTFOLIO-SELLPART');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NFLX', 'EVERLASTINGPORTFOLIO-SELLPART');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SFIX', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZG', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ISRG', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRM', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NVTA', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LOPE', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TWTR', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PJT', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NDSN', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('JD', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IRBT', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NTB', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VAC', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TCX', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FIT', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('UA', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('UAA', 'EVERLASTINGPORTFOLIO-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('GOOGL', 'EVERLASTINGPORTFOLIO-SELLFULL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CHUY', 'EVERLASTINGPORTFOLIO-SELLFULL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PRAA', 'EVERLASTINGPORTFOLIO-SELLFULL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CTSH', 'EVERLASTINGPORTFOLIO-SELLFULL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PII', 'EVERLASTINGPORTFOLIO-SELLFULL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BIDU', 'EVERLASTINGPORTFOLIO-SELLFULL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPB', 'EVERLASTINGPORTFOLIO-SELLFULL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('GOOG', 'EVERLASTINGPORTFOLIO-SELLPART');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'EVERLASTINGPORTFOLIO-BUY');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LMND', 'EVERLASTINGPORTFOLIO-BUY');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FVRR', 'EVERLASTINGPORTFOLIO-BUY');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRWD', 'EVERLASTINGPORTFOLIO-BUY');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WORK', 'TheOwnershipPortfolio-SELL');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LMND', 'TheOwnershipPortfolio-BUY');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FVRR', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SDGR', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PINS', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRWD', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WD', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TTD', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NVTA', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'TheOwnershipPortfolio-BUYMORE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FLGT', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TSLA', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FSLY', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDB', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZS', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ANET', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LOB', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OPEN', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HUBS', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SQ', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ESTC', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CLOV', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPOT', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SHOP', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TXG', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PAYC', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DDOG', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIX', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LSF', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FB', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NOW', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('KNSL', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VITL', 'TheOwnershipPortfolio-HOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FSLY', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZS', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDB', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NVDA', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DDOG', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('GLOB', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('AVLR', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DAVA', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TSM', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MSFT', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('AMZN', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('EQIX', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LRCX', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPOT', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PLAN', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRM', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NOW', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DLR', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HUBS', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NCNO', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SNOW', 'CloudDisruptors-BuyMore');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NET', 'CloudDisruptors-Buy');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('AMT', 'CloudDisruptors-Hold');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ACN', 'CloudDisruptors-Hold');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPLK', 'CloudDisruptors-Hold');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BABA', 'CloudDisruptors-Hold');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IPOD.U', 'RisingStars-SCOUT');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IPOE.U', 'RisingStars-SCOUT');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IPOF.U', 'RisingStars-SCOUT');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ETSY', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FLGT', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FSLY', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FVRR', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('GLOB', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HUBS', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('KNSL', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MGNI', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WD', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIX', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZS', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LMND', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OPEN', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LSF', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VITL', 'RisingStars-GOLD');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPF', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BOMN', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FIVN', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('INSP', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LOB', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NEO', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NVTA', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PD', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('RDFN', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SFIX', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPCE', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SRG', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VCYT', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CLOV', 'RisingStars-SILVER');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('AVAV', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CARG', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CBIZ', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CWBHF', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FRPT', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HCAT', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HQY', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LEGH', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LOPE', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDLA', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NEWR', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PHR', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PRLB', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('RVLV', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SMAR', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SONO', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VBK', 'RisingStars-BRONZE');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('AAPN', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BTC', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRWD', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ETSY', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FLGT', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LMND', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PINS', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SKLZ', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'Fool-10X');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PINS', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LMND', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FVRR', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FLGT', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OPEN', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('KSNL', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TTD', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRWD', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IPOE', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZS', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DDOG', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ROKU', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ETSY', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OKTA', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PLTR', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IPOD', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CLOV', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IPOF', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ESTC', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TXG', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPOT', 'IPO-Trailblazers-HighConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SFIX', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDB', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FSLY', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SNOW', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TDOC', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BOMN', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPCE', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPF', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('EXPI', 'IPO-Trailblazers-MediumConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PHR', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NCNO', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PD', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PTON', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TWLO', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('INSP', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('EVBG', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CARG', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SWAV', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CWEB', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LEGH', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SMAR', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HLI', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PING', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDLA', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HCAT', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('RVLV', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TMDX', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OLLI', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LKNC.Y', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SONO', 'IPO-Trailblazers-LowerConviction');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SEHK:3960', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MELI', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PAGS', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('API', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('JD', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('STN', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('STNE', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SHOP', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SE', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIX', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('YNDX', 'GlobalPartners');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TSLA', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SHOP', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TTD', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('KNSL', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MKTX', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MA', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('EQIX', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ANET', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BAM', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZS', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TWLO', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PRLB', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WD', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIX', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HUBS', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NOW', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WORK', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PAYC', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MCO', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OKTA', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SBUX', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDB', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SH', 'MoneyMakers');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'PartnershipPortfolioGroup1');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SHOP', 'PartnershipPortfolioGroup1');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TSLA', 'PartnershipPortfolioGroup1');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIX', 'PartnershipPortfolioGroup1');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'PartnershipPortfolioGroup1');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'PartnershipPortfolioGroup2');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'PartnershipPortfolioGroup2');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDB', 'PartnershipPortfolioGroup2');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OKTA', 'PartnershipPortfolioGroup2');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TTD', 'PartnershipPortfolioGroup2');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ANET', 'PartnershipPortfolioGroup3');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SQ', 'PartnershipPortfolioGroup3');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SFIX', 'PartnershipPortfolioGroup3');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TWLO', 'PartnershipPortfolioGroup3');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WD', 'PartnershipPortfolioGroup3');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPF', 'PartnershipPortfolioGroup4');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('EPAM', 'PartnershipPortfolioGroup4');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PAYC', 'PartnershipPortfolioGroup4');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('QTWO', 'PartnershipPortfolioGroup4');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRWD', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PINS', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LMND', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FVRR', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NFLX', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MTCH', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MASI', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DIS', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NVDA', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ABNB', 'StockAdvisor');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SHOP', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FB', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZM', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TSLA', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('KNSL', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TTD', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIX', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ZS', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ANET', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MA', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PJT', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MKL', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LOPE', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VTI', 'EverlastingStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('COUP', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FIVN', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IRBT', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('KNSL', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MDB', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NVEE', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PJT', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('QTWO', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SFIX', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TTD', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WD', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('APPN', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NTB', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BZUN', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('BLX', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WIFI', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CARE', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ICBK', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CWGL', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CRSP', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DHIL', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('EIG', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('FPI', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('INBK', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('GIII', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('HMTV', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LGIH', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MMYT', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MLAB', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NRC', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NRIM', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OTCM', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('RTM', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TLND', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TRUP', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TCX', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VREX', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('VRNS', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WINA', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('YTRA', 'RisingStarsDiscovery');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ALGN', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ANET', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('AUB', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TEAM', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CPF', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('CMG', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DHIL', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('EIG', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('GNTX', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('GIMO', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LOPE', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ASR', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ICON', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('ITIC', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IONS', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('IRBT', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('LHCG', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('MIDD', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NTUS', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('EGOV', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NVEE', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('OAK', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('PAYC', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SHOP', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('SPLK', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TXRH', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('TCX', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('UA', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('WAB', 'NextHomeRunStocks');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('POWW', 'TheStreetStocksUnder10');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('DBI', 'TheStreetStocksUnder10');

INSERT INTO VEN.STOCKRECOMMENDATIONTABLE (STOCKSYMBOL, RECOMMENDEDBY) VALUES ('NOK', 'TheStreetStocksUnder10');


